version: '3.3'
services:
  traefik:
    image: traefik:latest
    ports:
      - "99:99"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--entrypoints.main.address=:99"
      - "--providers.docker.allowEmptyServices=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - traefik
  cassandra:
    image: cassandra:latest
    restart: always
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - cassandra
      - coin
      - user_backend
      - scheduling

  cassandra-load-keyspace:
    image: cassandra:latest
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./database/cassandra/src/cassandra_schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - cassandra

  react-ui:
    build: ./website/frontend/user-interface
    restart: always
    depends_on:
      user-backend:
        condition: service_started
    networks:
      - website
      - traefik
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-ui.entrypoints=main"
      - "traefik.http.routers.react-ui.rule=PathPrefix(`/`)"
      - "traefik.http.services.react-ui.loadbalancer.server.port=80"
      - "traefik.docker.network=website"

  user-backend:
    build: ./website/backend
    restart: always
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-load-keyspace:
        condition: service_completed_successfully
      auth-service:
        condition: service_started
      coin-service:
        condition: service_started
    command:
      - "--authentication_uri=http://auth-service:7979"
      - "--cassandra_uri=cassandra"
      - "--cassandra_port=9042"
      - "--cassandra_user=cassandra"
      - "--cassandra_passwd=cassandra"
      - "--coinservice_uri=http://coin-service:1337"
    networks:
      - website
      - coin
      - user_backend
      - traefik
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-backend.entrypoints=main"
      - "traefik.http.routers.user-backend.rule=PathPrefix(`/api`)"
      - "traefik.http.services.user-backend.loadbalancer.server.port=6543"
      - "traefik.http.middlewares.user-backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.user-backend-stripprefix.stripprefix.forceSlash=true"
      - "traefik.http.routers.user-backend.middlewares=user-backend-stripprefix"

  auth-service:
    build: ./authentitication/server
    restart: always
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-load-keyspace:
        condition: service_completed_successfully
    command:
      - "--cassandra_uri=cassandra"
      - "--cassandra_port=9042"
      - "--cassandra_user=cassandra"
      - "--cassandra_passwd=cassandra"
    networks:
      - user_backend
    deploy:
        replicas: 1

  mining-server:
    build: ./mining/server
    networks:
      - mining_backend
      - mining
      - scheduling
      - rabbitmq_network
      - coin
      - traefik
    command:
      - "--redis_uri=scheduling-store"
      - "--redis_port=6379"
      - "--rabbitMQ_uri=rabbitmq"
      - "--rabbitMQ_user=user"
      - "--rabbitMQ_passwd=user"
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mining-server.entrypoints=main"
      - "traefik.http.routers.mining-server.rule=PathPrefix(`/miningServer`)"
      - "traefik.http.services.mining-server.loadbalancer.sticky.cookie.name=stick"
      - "traefik.http.services.mining-server.loadbalancer.server.port=8000"
      # strip prefix
      - "traefik.http.middlewares.mining-server-stripprefix.stripprefix.prefixes=/miningServer"
      - "traefik.http.middlewares.mining-server-stripprefix.stripprefix.forceSlash=true"
      - "traefik.http.routers.mining-server.middlewares=mining-server-stripprefix"
      # - "traefik.backend.loadbalancer.stickiness=true"

  result-server:
    build: ./result/server
    networks:
      - mining_backend
      - mining
      - scheduling
      - rabbitmq_network
      - traefik
    command:
      - "--redis_uri=scheduling-store"
      - "--redis_port=6379"
      - "--task_db_number=0"
      - "--socketio_db_number=1"
      - "--rabbitMQ_uri=rabbitmq"
      - "--rabbitMQ_user=user"
      - "--rabbitMQ_passwd=user"
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.result-server.entrypoints=main"
      - "traefik.http.routers.result-server.rule=PathPrefix(`/resultServer`)"
      - "traefik.http.services.result-server.loadbalancer.sticky.cookie.name=stick"
      - "traefik.http.services.result-server.loadbalancer.server.port=8000"
        # strip prefix
      - "traefik.http.middlewares.result-server-stripprefix.stripprefix.prefixes=/resultServer"
      - "traefik.http.middlewares.result-server-stripprefix.stripprefix.forceSlash=true"
      - "traefik.http.routers.result-server.middlewares=result-server-stripprefix"

  scheduling-service:
    build: ./scheduling/server
    restart: always
    command:
      - "--cassandra_uri=cassandra"
      - "--cassandra_port=9042"
      - "--cassandra_user=cassandra"
      - "--cassandra_passwd=cassandra"
      - "--redis_uri=scheduling-store"
      - "--redis_port=6379"
      - "--manager_uri=http://manager"
      - "--manager_port=666"
    networks:
      - scheduling
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-load-keyspace:
        condition: service_completed_successfully
      scheduling-store:
        condition: service_started
    deploy:
      replicas: 1

  scheduling-store:
    image: redis:7.0-alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - scheduling

  manager:
    build: ./scheduling/manager
    networks:
      - scheduling

  coin-service:
    build: ./coin
    command:
      - "--cassandra_uri=cassandra"
      - "--cassandra_port=9042"
      - "--cassandra_user=cassandra"
      - "--cassandra_passwd=cassandra"
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-load-keyspace:
        condition: service_completed_successfully
    networks:
      - coin

#  nginx:
#    image: nginx:latest
#    ports:
#      - "99:99"
#    volumes:
#      - ./loadbalancer/nginx/nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - react_ui
#      - mining_server
#      - result_server
#    networks:
#      - website
#      - mining

  rabbitmq:
    image: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - rabbitmq_network

networks:
  traefik:
  website:
  scheduling:
  mining:
  coin:
  user_backend:
  mining_backend:
  cassandra:
  rabbitmq_network: