version: '3.3'
services:

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    restart: always
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - website
      - scheduling
      - mining

  cassandra-load-keyspace:
    container_name: load-keyspace
    image: cassandra:latest
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./database/cassandra/src/cassandra_schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - website
      - scheduling
      - mining

  react_ui:
    container_name: react-ui
    build: ./website/frontend/user-interface
    ports:
      - "99:99"
    depends_on:
      user_backend:
        condition: service_started
    networks:
      - website

  user_backend:
    build: ./website/backend
    ports:
      - "6543:6543"
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-load-keyspace:
        condition: service_completed_successfully
      auth_service:
        condition: service_started
    command:
      - "--authentication_uri=http://auth_service:7979"
      - "--cassandra_uri=cassandra"
      - "--cassandra_port=9042"
      - "--cassandra_user=cassandra"
      - "--cassandra_passwd=cassandra"
    networks:
      - website

  auth_service:
    build: ./authentitication/server
    ports:
      - "7979:7979"
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-load-keyspace:
        condition: service_completed_successfully
    command:
      - "--cassandra_uri=cassandra"
      - "--cassandra_port=9042"
      - "--cassandra_user=cassandra"
      - "--cassandra_passwd=cassandra"
    networks:
      - mining
      - website
  #mining_server:
  #  build: ./mining/server
  #  ports:
  #    - "80:80"
  #    - "443:443"
 #   networks:
   #   - mining
    #  - scheduling

  scheduling_service:
    build: ./scheduling
    command:
      - "--cassandra_uri=cassandra"
      - "--cassandra_port=9042"
      - "--cassandra_user=cassandra"
      - "--cassandra_passwd=cassandra"
      - "--redis_uri=scheduling_store"
      - "--redis_port=6379"
    networks:
      - scheduling
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-load-keyspace:
        condition: service_completed_successfully
      scheduling_store:
        condition: service_started
  #mining_store:
  #  image: redis:7.0-alpine
  #  restart: always
  #  environment:
  #    - ALLOW_EMPTY_PASSWORD=yes
  #  ports:
  #    - '6379:6379'
  scheduling_store:
    image: redis:7.0-alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - scheduling

networks:
  website:
    external: true
  scheduling:
    external: false
  mining:
    external: true