version: '3.3'
services:

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    restart: always
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - cassandra
      - coin
      - user_backend
      - scheduling

  cassandra-load-keyspace:
    container_name: load-keyspace
    image: cassandra:latest
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./database/cassandra/src/cassandra_schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - cassandra

  react_ui:
    container_name: react-ui
    build: ./website/frontend/user-interface
    restart: always
    ports:
      - "99:99"
    depends_on:
      user_backend:
        condition: service_started
    networks:
      - website

  user_backend:
    build: ./website/backend
    ports:
      - "6543:6543"
    restart: always
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-load-keyspace:
        condition: service_completed_successfully
      auth_service:
        condition: service_started
      coin_service:
        condition: service_started
    command:
      - "--authentication_uri=http://auth_service:7979"
      - "--cassandra_uri=cassandra"
      - "--cassandra_port=9042"
      - "--cassandra_user=cassandra"
      - "--cassandra_passwd=cassandra"
      - "--coinservice_uri=http://coin_service:1337"
    networks:
      - website
      - coin
      - user_backend

  auth_service:
    build: ./authentitication/server
    restart: always
    ports:
      - "7979:7979"
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-load-keyspace:
        condition: service_completed_successfully
    command:
      - "--cassandra_uri=cassandra"
      - "--cassandra_port=9042"
      - "--cassandra_user=cassandra"
      - "--cassandra_passwd=cassandra"
    networks:
      - mining_backend
      - user_backend

  mining_server:
    build: ./mining/server
    ports:
      - "8001:8001"
    networks:
      - mining_backend
      - mining
      - scheduling

  result_server:
    build: ./result/server
    ports:
      - "8001:8000"
    networks:
      - mining_backend
      - mining

  scheduling_service:
    build: ./scheduling
    restart: always
    command:
      - "--cassandra_uri=cassandra"
      - "--cassandra_port=9042"
      - "--cassandra_user=cassandra"
      - "--cassandra_passwd=cassandra"
      - "--redis_uri=scheduling_store"
      - "--redis_port=6379"
    networks:
      - scheduling
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-load-keyspace:
        condition: service_completed_successfully
      scheduling_store:
        condition: service_started

  scheduling_store:
    image: redis:7.0-alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - scheduling

  coin_service:
    build: ./coin
    command:
      - "--cassandra_uri=cassandra"
      - "--cassandra_port=9042"
      - "--cassandra_user=cassandra"
      - "--cassandra_passwd=cassandra"
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-load-keyspace:
        condition: service_completed_successfully
    networks:
      - coin

networks:
  website:
    external: true
  scheduling:
    internal: true
  mining:
    external: true
  coin:
    internal: true
  user_backend:
    internal: true
  mining_backend:
    internal: true
  cassandra:
    internal: true