version: '3.3'
services:

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    restart: always
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: load-keyspace
    image: cassandra:latest
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./database/cassandra/src/cassandra_schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  react_ui:
    container_name: react-ui
    build: ./website/frontend/user-interface
    ports:
      - "99:99"
    expose:
      - 99
    depends_on:
      user_backend:
        condition: service_started

  user_backend:
    build: ./website/backend
    ports:
      - "6543:6543"
    expose:
      - 6543
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-load-keyspace:
        condition: service_completed_successfully
      auth_service:
        condition: service_started
    command:
      - "--authentication_uri=http://host.docker.internal:7979"
      - "--cassandra_uri=host.docker.internal"
      - "--cassandra_port=9042"
      - "--cassandra_user=cassandra"
      - "--cassandra_passwd=cassandra"

  auth_service:
    build: ./authentitication/server
    ports:
      - "7979:7979"
    expose:
      - 7979
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-load-keyspace:
        condition: service_completed_successfully
    command:
      - "--cassandra_uri=host.docker.internal"
      - "--cassandra_port=9042"
      - "--cassandra_user=cassandra"
      - "--cassandra_passwd=cassandra"