version: '3.3'
services:
  user_backend:
    build: .
    ports:
      - "6543:6543"
    expose:
      - 6543
    command:
      - "--authentication_uri=http://host.docker.internal:7979"
      - "--cassandra_uri=host.docker.internal"
      - "--cassandra_port=9042"
      - "--cassandra_user=cassandra"
      - "--cassandra_passwd=cassandra"