validate_user_credentials = "/token"
create_user = "/user/create"
get_user_by_token = "/user/get_by_token"
initial_otp_verify_path = "/user/initial_otp_verify"
check_credential = "/check_credentials"
update_coin = "/update_coin"
get_coin = "/get_coin"
